services:
  acme-dns:
    image: acme-dns:v2.0.2
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80/tcp"
    volumes:
      - ./config.cfg:/etc/acme-dns/config.cfg:ro
      - ./data:/var/lib/acme-dns
